version: '3.5'
services:
  jupyter:
    image: lobnek/jupyter
    build:
       context: .
       dockerfile: jupyter/Dockerfile
    volumes:
       - /media/j/notebooks:/home/${NB-USER}/work
    ports:
       - ${PORT}:8888

  docker:
    image: lobnek/docker
    build:
      context: .
      dockerfile: lobnek/Dockerfile
      target: builder

  sut:
    image: lobnek/sut
    build:
       context: .
       dockerfile: lobnek/Dockerfile
       target: test

    volumes:
        - ./test:/docker/test:ro
