version: '3.4'
services:
  sut:
     build:
       context: .
       dockerfile: Dockerfile
       target: test

     volumes:
        - ./test:/docker/test:ro

     links:
       - test-postgresql

  test-postgresql:
    image: postgres:9.6
