version: '3.5'
services:
  jupyter:
     build:
       context: .
       dockerfile: Dockerfile-Jupyter
     volumes:
       - /media/j/notebooks:/home/${NB-USER}/work
     ports:
       - ${PORT}:8888
  docker:
    build:
      context: .
      dockerfile: Dockerfile

