version: '3.5'
services:
  web:
     build:
       context: .
       dockerfile: Dockerfile-Jupyter
     volumes:
       - /media/j/notebooks:/home/beakerx/work
     command:
       - /bin/bash

  lobnek:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    command:
      - /bin/bash
