version: '3.5'
services:
  jupyter:
     build:
       context: .
       dockerfile: jupyter/Dockerfile
     volumes:
       - /media/j/notebooks:/home/${NB-USER}/work
     ports:
       - ${PORT}:8888
  docker:
    build:
      context: .
      dockerfile: lobnek/Dockerfile
      target: builder

  sut:
     build:
       context: .
       dockerfile: lobnek/Dockerfile
       target: test

     volumes:
        - ./test:/docker/test:ro
