version: '3.5'
services:
  jupyter:
    image: lobnek/jupyterx
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
       - /media/j/notebooks:${WORK}
    ports:
       - ${PORT}:8888
